/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TestResponseBody
 */
public class TestResponseBodyTest {
    private final TestResponseBody model = new TestResponseBody();

    /**
     * Model tests for TestResponseBody
     */
    @Test
    public void testTestResponseBody() {
        // TODO: test TestResponseBody
    }

    /**
     * Test the property 'requiredField'
     */
    @Test
    public void requiredFieldTest() {
        // TODO: test requiredField
    }

    /**
     * Test the property 'requiredNullableField'
     */
    @Test
    public void requiredNullableFieldTest() {
        // TODO: test requiredNullableField
    }

    /**
     * Test the property 'optionalField'
     */
    @Test
    public void optionalFieldTest() {
        // TODO: test optionalField
    }

    /**
     * Test the property 'optionalNullableField'
     */
    @Test
    public void optionalNullableFieldTest() {
        // TODO: test optionalNullableField
    }

    /**
     * Test the property 'requiredArrayField'
     */
    @Test
    public void requiredArrayFieldTest() {
        // TODO: test requiredArrayField
    }

    /**
     * Test the property 'requiredNullableArrayField'
     */
    @Test
    public void requiredNullableArrayFieldTest() {
        // TODO: test requiredNullableArrayField
    }

    /**
     * Test the property 'optionalArrayField'
     */
    @Test
    public void optionalArrayFieldTest() {
        // TODO: test optionalArrayField
    }

    /**
     * Test the property 'optionalNullableArrayField'
     */
    @Test
    public void optionalNullableArrayFieldTest() {
        // TODO: test optionalNullableArrayField
    }

    /**
     * Test the property 'requiredObjectField'
     */
    @Test
    public void requiredObjectFieldTest() {
        // TODO: test requiredObjectField
    }

    /**
     * Test the property 'requiredNullableObjectField'
     */
    @Test
    public void requiredNullableObjectFieldTest() {
        // TODO: test requiredNullableObjectField
    }

    /**
     * Test the property 'optionalObjectField'
     */
    @Test
    public void optionalObjectFieldTest() {
        // TODO: test optionalObjectField
    }

    /**
     * Test the property 'nullableObjectField'
     */
    @Test
    public void nullableObjectFieldTest() {
        // TODO: test nullableObjectField
    }

}
